version: "2"

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./certbot:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
  certbot:
    image: certbot/certbot
    volumes:
      - "./certbot:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - "3000:3000"
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    volumes:
      - "./.:/client"
    links:
      - api
    ports:
      - "5000:80"
