version: "2"

services:
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - "3000:3000"
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    volumes:
      - "./.:/client"
    links:
      - api
    ports:
      - "5000:80"