version: "2"

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - webappnetwork
    depends_on:
      - client
      - api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
      image: certbot/certbot
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      networks:
        - webappnetwork
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - webappnetwork
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    volumes:
      - "./.:/client"
    links:
      - api
    ports:
      - "5000:80"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
    external: true
