version: "2"

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./packages/admin/build:/usr/share/nginx/admin/html
      - ./packages/client/build:/usr/share/nginx/client/html
      - ./packages/landing/dist:/usr/share/nginx/landing/html
  certbot:
      image: certbot/dns-cloudflare
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
        - ./data/certbot/cloudflareapi.ini:/var/www/cloudflareapi.ini
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - webappnetwork
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./.:/client"
      - ./packages/admin/build:/usr/share/nginx/admin/html
      - ./packages/client/build:/usr/share/nginx/client/html
      - ./packages/landing/dist:/usr/share/nginx/landing/html
    links:
      - api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
