branch-defaults:
  dungnq:
    environment: Apieb-env
  master:
    environment: Apieb-env
    group_suffix: null
global:
  application_name: api-eb
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
version: 2
