version: 2.1
orbs:
  node: circleci/node@4.2.0

aliases:
  - &docker-image
    docker:
      - image: cimg/node:14.15.4

  - &install_typescript_globally
    run:
      name: intall typescript globally
      command: yarn global add typescript

commands:
  node-build-steps:
    steps:
      - checkout:
          path: ~/lcm-system
      - run:
          name: Install Dependencies
          command: |
            yarn install
            yarn install:all
      - run:
          name: Deploy
          command: yarn deploy

jobs:
  deploy:
    docker:
      - image: cimg/node:14.15.4
    working_directory: ~/lcm-system

    steps:
      - node-build-steps
workflows:
  api:
    jobs:
      - deploy
