version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.2

workflows:
  build-and-test:
    jobs:
      - eb/deploy:
          context: Apieb-env
          environment-name: Apieb-env
          filters:
            branches:
              only:
                - master
          label: version-1
