version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v dungnq@66.42.52.219 "./deploy.sh"

workflows:
  deploy:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
