version: 2.1
orbs:
  node: circleci/node@4.2.0

aliases:
  - &docker-image
    docker:
      - image: cimg/node:14.15.4

  - &install_typescript_globally
    run:
      name: intall typescript globally
      command: yarn global add typescript

commands:
  save-build-flag:
    steps:
      - run:
          name: Create Build Flag
          command: touch build.flag
      - save_cache:
          paths:
            - build.flag
          key:
            build-flag={{ checksum "package.json" }}

  node-build-steps:
    steps:
      - checkout:
          path: ~/lcm-system
      - run:
          name: Build
          command: |
            yarn install
            yarn install:all
      - run:
          name: Start
          command: yarn start

jobs:
  build-api:
    docker:
      - image: cimg/node:14.15.4
    working_directory: ~/lcm-system

    steps:
      - node-build-steps
workflows:
  api:
    jobs:
      - build-api
