version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./packages/api/
          profile-name: dungnq
          region: AWS_REGION_ENV_VAR_NAME
          repo: '${MY_APP_PREFIX}'
          skip-when-tags-exist: false
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=api,tag=latest'
          family: 'api'
          requires:
              - aws-ecr/build-and-push-image
